package com.shalab.calculator.gui;

import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.event.DocumentEvent;import javax.swing.event.DocumentListener;import java.awt.*;import java.util.List;import java.util.Locale;import java.util.stream.Collectors;

/** Searchable documentation view with topic navigation and structured topic details. */
public final class HelpPanel extends JPanel {
    private record Topic(String category,String title,String syntax,String formula,String example,String description,String units) { String searchable(){return (category+title+syntax+formula+example+description+units).toLowerCase(Locale.ROOT);} }
    private final List<Topic> topics=List.of(
      t("Calculator","Expression basics","2 + 3 * 4","Standard precedence: parentheses, powers, multiplication/division, addition/subtraction","2 + 3 × 4 = 14","Enter a complete arithmetic expression. % after a value means percent; infix % is modulo.","Unitless"),
      t("Scientific","Trigonometry","sin(angle), cos(angle), tan(angle)","Angle functions follow the DEG/RAD switch","DEG: sin(90) = 1","Inverse functions asin, acos and atan return angles in the selected mode.","Degrees or radians"),
      t("Scientific","Logarithms and roots","log(x), ln(x), sqrt(x), cbrt(x)","log is base 10; ln is natural log","sqrt(144) = 12; log(100) = 2","Logarithms require positive input. Square root requires non-negative input.","Real numbers"),
      t("Scientific","Powers and factorial","x^y, x!, exp(x)","x! = 1 × 2 × … × x","5! = 120; 2^10 = 1024","Factorial accepts whole numbers from 0 through 170. Constants pi, e and ANS are available.","Real numbers"),
      t("Electrical","Ohm's Law","V = I × R","Voltage equals current times resistance","I = 2 A, R = 10 Ω → V = 20 V","Fill any two of voltage, current, and resistance; calculate the third.","V, A, Ω"),
      t("Electrical","Electrical power","P = V × I","Power equals voltage times current","12 V × 5 A = 60 W","Enter voltage and current in the engineering card.","V, A, W"),
      t("Mechanics","Mechanics formulas","F=ma, KE=½mv², PE=mgh","Density m/V; momentum mv; work Fd; power W/t","m=2 kg, a=3 m/s² → F=6 N","Use consistent SI inputs; output units are shown by each formula card.","SI units"),
      t("Error Analysis","Measurement error","Absolute, relative and percentage error","|measured−true|; absolute/|true|; relative×100%","Measured 12, true 10 → 20% error","True value must be non-zero for relative and percentage errors.","Same units for both values"),
      t("Mathematics","Quadratic solver","ax² + bx + c = 0","D=b²−4ac; x=(−b±√D)/(2a)","x²−5x+6=0 → x=3, 2","Negative discriminant produces a pair of complex roots. Coefficient a cannot be zero.","Coefficients must be finite"),
      t("Converter","Unit conversion","Choose category, value, from and to","Linear units convert through a shared base; temperature uses scale offsets","100 centimeter = 1 meter","Length, mass, temperature, time, area and speed conversions are supported.","See unit selectors"),
      t("Shortcuts","Keyboard shortcuts","Enter, Escape, Backspace","Enter calculates; Escape clears; Backspace deletes","Type (2+3)*4 then press Enter","Number and operator keys can be typed directly in the expression field.","Calculator input"));
    private final DefaultListModel<String> model=new DefaultListModel<>();private final JList<String> list=new JList<>(model);private final JTextPane detail=new JTextPane();private final JTextField search=UITheme.field();
    public HelpPanel(){super(new BorderLayout(12,12));setBackground(UITheme.BACKGROUND);setBorder(new EmptyBorder(18,18,18,18));JLabel title=UITheme.label("Help & formula guide");title.setFont(UITheme.TITLE);
        JPanel head=UITheme.panel(new BorderLayout(8,8));head.add(title,BorderLayout.WEST);search.setToolTipText("Search formulas, examples, functions...");head.add(search,BorderLayout.SOUTH);
        list.setBackground(UITheme.SURFACE);list.setForeground(UITheme.TEXT);list.setFont(UITheme.BODY);list.setFixedCellHeight(40);list.setBorder(new EmptyBorder(6,8,6,8));JPanel nav=UITheme.card(new BorderLayout(4,4));nav.setPreferredSize(new Dimension(220,200));nav.add(UITheme.muted("TOPICS"),BorderLayout.NORTH);nav.add(new JScrollPane(list),BorderLayout.CENTER);
        detail.setEditable(false);detail.setContentType("text/html");detail.setBackground(UITheme.CARD);detail.setForeground(UITheme.TEXT);detail.setBorder(new EmptyBorder(18,20,18,20));JScrollPane detailScroll=new JScrollPane(detail);detailScroll.setBorder(BorderFactory.createLineBorder(UITheme.BORDER,1,true));detailScroll.getViewport().setBackground(UITheme.CARD);
        add(head,BorderLayout.NORTH);add(nav,BorderLayout.WEST);add(detailScroll,BorderLayout.CENTER);populate("");
        list.addListSelectionListener(e->{if(!e.getValueIsAdjusting())showSelected();});search.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){populate(search.getText());}public void removeUpdate(DocumentEvent e){populate(search.getText());}public void changedUpdate(DocumentEvent e){populate(search.getText());}});
    }
    private void populate(String query){String q=query.toLowerCase(Locale.ROOT).trim();model.clear();for(Topic topic:topics)if(q.isEmpty()||topic.searchable().contains(q))model.addElement(topic.category()+"  ·  "+topic.title());if(!model.isEmpty())list.setSelectedIndex(0);else detail.setText("<html><body style='color:#e8eef6;font-family:sans-serif'><h2>No matching topics</h2><p>Try another search term.</p></body></html>");}
    private void showSelected(){String selected=list.getSelectedValue();if(selected==null)return;String title=selected.substring(selected.indexOf('·')+1).trim();Topic t=topics.stream().filter(x->x.title().equals(title)).findFirst().orElse(null);if(t==null)return;
        String html="<html><body style='color:#e8eef6;font-family:sans-serif;font-size:14px'><div style='color:#97a6b9;font-size:12px'>"+escape(t.category().toUpperCase())+"</div><h1>"+escape(t.title())+"</h1><h3>Syntax</h3><p><code>"+escape(t.syntax())+"</code></p><h3>Formula</h3><p>"+escape(t.formula())+"</p><h3>Example</h3><p>"+escape(t.example())+"</p><h3>How it works</h3><p>"+escape(t.description())+"</p><h3>Units / domain</h3><p>"+escape(t.units())+"</p></body></html>";detail.setText(html);detail.setCaretPosition(0);}
    private static Topic t(String c,String title,String syntax,String formula,String example,String description,String units){return new Topic(c,title,syntax,formula,example,description,units);}private String escape(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
}
